# Generated by Django 3.2.3 on 2021-05-26 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210526_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.customer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='dealer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.dealer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='plot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.plot'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rebate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dues',
            name='deal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.deal'),
        ),
        migrations.AlterField(
            model_name='dues',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.deal'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_plots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
