# Generated by Django 3.2.3 on 2021-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('contact_no', models.TextField(blank=True, null=True, unique=True)),
                ('other_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('relation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Client_Relation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plot_id', models.IntegerField(blank=True, null=True)),
                ('cust_id', models.IntegerField(blank=True, null=True)),
                ('rebate', models.IntegerField(blank=True, null=True)),
                ('dealer_id', models.IntegerField(blank=True, null=True)),
                ('commission', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Deal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_id', models.IntegerField()),
                ('due_date', models.TextField(blank=True, null=True)),
                ('payable_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Dues',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_id', models.IntegerField()),
                ('date', models.TextField(blank=True, null=True)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('interest', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plot_no', models.TextField()),
                ('project_id', models.IntegerField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Plot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('total_plots', models.IntegerField(blank=True, db_column='total_pLots', null=True)),
            ],
            options={
                'db_table': 'Project',
                'managed': True,
            },
        ),
    ]
