# Generated by Django 3.2.3 on 2021-05-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('contact_no', models.TextField(blank=True, null=True, unique=True)),
                ('other_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('contact_no', models.TextField(blank=True, null=True, unique=True)),
                ('other_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Dealer',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientRelation',
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dues',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True},
        ),
    ]
