# Generated by Django 3.2.3 on 2021-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210526_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dues',
            new_name='Due',
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='contact_no',
            field=models.TextField(null=True, unique=True),
        ),
    ]
