# Generated by Django 3.2.3 on 2021-05-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_plot_plot_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='cust_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='dealer_id',
            new_name='dealer',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='plot_id',
            new_name='plot',
        ),
        migrations.RenameField(
            model_name='due',
            old_name='deal_id',
            new_name='deal',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='deal_id',
            new_name='deal',
        ),
        migrations.RenameField(
            model_name='plot',
            old_name='project_id',
            new_name='project',
        ),
    ]
