# Generated by Django 3.2.3 on 2021-05-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20210527_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='plot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.plot'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='Home.project'),
        ),
    ]
