# Generated by Django 3.2.4 on 2021-06-15 06:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_plot_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='interest',
            new_name='interest_given',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount_paid',
            new_name='net_amount_paid',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='rebate',
        ),
        migrations.AddField(
            model_name='payment',
            name='rebate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals', to='Home.customer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deals', to='Home.dealer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='plot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deal', to='Home.plot'),
        ),
        migrations.AlterField(
            model_name='due',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dues', to='Home.deal'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Home.deal'),
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('amount', models.FloatField()),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='Home.deal')),
            ],
            options={
                'verbose_name': 'Commission Payment',
                'db_table': 'CommissionPayment',
                'managed': True,
            },
        ),
    ]
