# Generated by Django 3.2.4 on 2021-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20210615_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='contact_no',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
