# Generated by Django 3.2.4 on 2021-07-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20210615_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionpayment',
            options={'managed': True, 'ordering': ['date'], 'verbose_name': 'Commission Payment'},
        ),
        migrations.AlterModelOptions(
            name='due',
            options={'managed': True, 'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': True, 'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='plot',
            name='plc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='plot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='Home.plot'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='contact_no',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
