# Generated by Django 3.2.4 on 2021-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_plot_plot_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='due',
            name='payable_amount',
        ),
        migrations.AddField(
            model_name='due',
            name='payable_amount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
